fix: RoleCache.has_role should be case-insensitive
nelc/edx-platform pull request #35
Opened 2024-08-15 12:21 UTC by shadinaif

## Description

`RoleCache` compares `org` in a case-sensitive manner where the value of `org` is assumed as case-insensitive by the database collation, and by the [django admin form](https://github.com/openedx/edx-platform/blob/059f8338045c4465cd2086403069d5521c773e18/common/djangoapps/student/admin.py#L154). This PR is to fix the issue to make `RoleCache` behaves as the rest of the platform

## Supporting information

-------

## Testing instructions

**Steps to test:**
* Assume a normal user in the platform, for example `test_user`
* Assuming we have two courses in `demo` organization: `course-v1:Demo+topic1+index1` and `course-v1:demo+topic2+index2`. We have the first course with organization `Demo` in course-overview instead of `demo`. This is acceptable in the platform

**Before the fix:**
* The admin will not be able to grant `test_user` an `instructor` on the entire `demo` organization, the admin will have to grant it course by course. This is because `CourseAccessRole` will not accept two similar records like `[user: test_user, course_id: "", role: instructor, org: demo]` and `[user: test_user, course_id: "", role: instructor, org: Demo]`. The key treats `org` as case-insensitive

**After the fix:**
* Adding a single record like `[user: test_user, course_id: "", role: instructor, org: demo]`, `[user: test_user, course_id: "", role: instructor, org: Demo]`, or even `[user: test_user, course_id: "", role: instructor, org: DEMO]` will make `test_user` an instructor on all courses as expected

## Deadline

-----------

## Other information

------------

2024-08-15 12:23 UTC, shadinaif commented
I'll contribute this to Upstream once we have a code review here

2024-08-16 06:51 UTC, OmarIthawi approved these changes

2024-08-16 07:37 UTC, OmarIthawi requested changes
@shadinaif few minor notes regarding testing. They're important for upstream contribution.

2024-08-16 10:57 UTC, shadinaif commented on common/djangoapps/student/tests/test_roles.py
> +        (CourseStaffRole(IN_KEY), ('staff', IN_KEY, 'EDX')),
sounds reasonable, thank you!

2024-08-16 10:59 UTC, shadinaif commented on common/djangoapps/student/tests/test_roles.py
> +        (CourseStaffRole(IN_KEY), ('staff', IN_KEY, 'EDX')),
it'll not work exactly like this because the test iterates on all records, but I'll find a way 👍🏼

2024-08-16 11:09 UTC, shadinaif commented on common/djangoapps/student/tests/test_roles.py
> +        (CourseStaffRole(IN_KEY), ('staff', IN_KEY, 'EDX')),
Done 👍🏼

2024-08-16 13:42 UTC, OmarIthawi requested changes
@shadinaif please note that I think the fix in the code is pretty fine.

I'm just reviewing with very high quality standards i.e. upstream quality, let me know if you think we should stop and focus on making the fix locally and then worry about upstream contribution.

2024-08-16 13:42 UTC, OmarIthawi commented on common/djangoapps/student/tests/test_roles.py
> +            assert cache.has_role(*other_target) == (test_id == other_test_id)
@shadinaif I presume I'm very familiar with the issue being presented here, but the test still isn't understanble.

I think the real cause is that the original `test_only_in_role` function was cryptic.

In such case I would support creating a new test case e.g. `test_only_in_role_case_insensitive` so it doesn't have for-loop or at least it doesn't have to be so generic and becomes hard to understand.

2024-08-18 13:16 UTC, shadinaif commented
I've update the tests @OmarIthawi I believe it's clear now

2024-08-18 14:06 UTC, OmarIthawi approved these changes
super!

2024-08-19 06:32 UTC, merged

2024-09-09 21:40 UTC, andrey-canon commented
hi @OmarIthawi and @shadinaif, just asking, is this a backport? Or is there an equivalent upstream PR?

2024-09-10 08:44 UTC, shadinaif commented
unfortunately, it's not equivalent to upstream. When I tried to create a PR, I found that the code there had changed and a cherry-pick was not possible. I'm planning to report/fix upstream by the end of this month. I'll keep updated @andrey-canon , thank you for checking 👍🏼

2024-09-10 11:43 UTC, OmarIthawi commented
Thanks @shadinaif!!

2024-09-10 17:41 UTC, andrey-canon commented
Hi @shadinaif thanks for you answer and I was asking because we have a migration [file](https://docs.google.com/spreadsheets/d/1MB97ieTmUdyyte9elBcHub4D7lsrcaKe0kN6WDRN0WI/edit?gid=0#gid=0) where we track all the custom commits. This file helps us to decide which commits we must include in the next release, so if the commit is not there  there is a chance that we will miss it, so  could you please add the commit data into the file?
please check the section [colors](https://docs.google.com/spreadsheets/d/1MB97ieTmUdyyte9elBcHub4D7lsrcaKe0kN6WDRN0WI/edit?gid=255958755#gid=255958755) and change the row color

2024-09-11 04:49 UTC, shadinaif commented
Thank you @andrey-canon . I've added it as gray and explained the reason in the sheet. The fix is needed, but this code should be discarded in the upgrade process (this is why I set it as gray). I'll follow up with you after having the fix in upstream

2024-09-11 16:05 UTC, andrey-canon commented
> d be discarded in the upgrade process (this is why I set it as gray). I'll follow up with you after having the fix in upstream

thanks @shadinaif